# olist orders dataset

In [1]:
import pandas as pd
import os

In [2]:
orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

In [3]:
#show the first five rows of the dataset
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [4]:
#show the number of rows and columns in the dataset
orders.shape

(99441, 8)

In [5]:
#show column names,  non null values, and data types
orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 6.1 MB

In [6]:
#counts missing values in each column
orders.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [7]:
#check for exact dupliacte rows
orders.duplicated().sum()

np.int64(0)

In [8]:
print("Rows:", orders.shape[0])
print("Columns:", orders.shape[1])
print("Exact duplicate rows:", orders.duplicated().sum())
print("\nMissing values per column:")
print(orders.isnull().sum())
print("\nData types:")
print(orders.dtypes)

Rows: 99441
Columns: 8
Exact duplicate rows: 0

Missing values per column:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Data types:
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [10]:
missing_summary = orders.isnull().sum()

missing_summary = missing_summary[missing_summary > 0]

print(missing_summary)

order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

In [11]:
missing_percent = (
    orders.isnull().mean() * 100
).round(2)

missing_percent = missing_percent[missing_percent > 0]

print(missing_percent)

order_approved_at                0.16
order_delivered_carrier_date     1.79
order_delivered_customer_date    2.98
dtype: float64

In [12]:
orders[orders.isnull().any(axis=1)].head(10)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
6,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,NaN,NaN,2017-05-09 00:00:00
44,ee64d42b8cf066f35eac1cf57de1aa85,caded193e8e47b8362864762a83db3c5,shipped,2018-06-04 16:44:48,2018-06-05 04:31:18,2018-06-05 14:32:00,NaN,2018-06-28 00:00:00
103,0760a852e4e9d89eb77bf631eaaf1c84,d2a79636084590b7465af8ab374a8cf5,invoiced,2018-08-03 17:44:42,2018-08-07 06:15:14,NaN,NaN,2018-08-21 00:00:00
128,15bed8e2fec7fdbadb186b57c46c92f2,f3f0e613e0bdb9c7cee75504f0f90679,processing,2017-09-03 14:22:03,2017-09-03 14:30:09,NaN,NaN,2017-10-03 00:00:00
154,6942b8da583c2f9957e990d028607019,52006a9383bf149a4fb24226b173106f,shipped,2018-01-10 11:33:07,2018-01-11 02:32:30,2018-01-11 19:39:23,NaN,2018-02-07 00:00:00
162,36530871a5e80138db53bcfd8a104d90,4dafe3c841d2d6cc8a8b6d25b35704b9,shipped,2017-05-09 11:48:37,2017-05-11 11:45:14,2017-05-11 13:21:47,NaN,2017-06-08 00:00:00
231,4d630f57194f5aba1a3d12ce23e71cd9,6d491c9fe2f04f6e2af6ec033cd8907c,shipped,2017-11-17 19:53:21,2017-11-18 19:50:31,2017-11-22 17:28:34,NaN,2017-12-13 00:00:00
266,8e24261a7e58791d10cb1bf9da94df5c,64a254d30eed42cd0e6c36dddb88adf0,unavailable,2017-11-16 15:09:28,2017-11-16 15:26:57,NaN,NaN,2017-12-05 00:00:00
299,3b4ad687e7e5190db827e1ae5a8989dd,1a87b8517b7d31373b50396eb15cb445,shipped,2018-06-28 12:52:15,2018-06-28 13:11:09,2018-07-04 15:20:00,NaN,2018-08-03 00:00:00
305,b68d69564a79dea4776afa33d1d2fcab,de1e5517fb50896bbdcff5814fb31802,shipped,2018-02-28 08:57:03,2018-02-28 10:40:35,2018-03-05 16:10:13,NaN,2018-03-23 00:00:00

In [13]:
orders["order_status"].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [14]:
date_columns = [
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date"
]

for column in date_columns:
    print(f"\nMissing values in {column}:")

    print(
        orders.loc[
            orders[column].isna(),
            "order_status"
        ].value_counts()
    )

Missing values in order_approved_at:
order_status
canceled     141
delivered     14
created        5
Name: count, dtype: int64

Missing values in order_delivered_carrier_date:
order_status
unavailable    609
canceled       550
invoiced       314
processing     301
created          5
approved         2
delivered        2
Name: count, dtype: int64

Missing values in order_delivered_customer_date:
order_status
shipped        1107
canceled        619
unavailable     609
invoiced        314
processing      301
delivered         8
created           5
approved          2
Name: count, dtype: int64

In [15]:
delivered_missing = orders[
    (orders["order_status"] == "delivered") &
    (
        orders["order_delivered_customer_date"].isna() |
        orders["order_delivered_carrier_date"].isna()
    )
]

print("Delivered orders missing a delivery milestone:",
      len(delivered_missing))

delivered_missing.head(10)

Delivered orders missing a delivery milestone: 9

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
73222,2aa91108853cecb43c84a5dc5b277475,afeb16c7f46396c0ed54acb45ccaaa40,delivered,2017-09-29 08:52:58,2017-09-29 09:07:16,NaN,2017-11-20 19:44:47,2017-11-14 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [17]:
for column in date_columns:
    print(f"\n--- {column} ---")

    summary = (
        orders.groupby("order_status")[column]
        .agg(
            total_orders="size",
            missing_values=lambda x: x.isna().sum()
        )
    )

    summary["missing_percent"] = (
        summary["missing_values"] /
        summary["total_orders"] * 100
    ).round(2)

    print(summary)

--- order_approved_at ---
              total_orders  missing_values  missing_percent
order_status
approved                 2               0             0.00
canceled               625             141            22.56
created                  5               5           100.00
delivered            96478              14             0.01
invoiced               314               0             0.00
processing             301               0             0.00
shipped               1107               0             0.00
unavailable            609               0             0.00

--- order_delivered_carrier_date ---
              total_orders  missing_values  missing_percent
order_status
approved                 2               2            100.0
canceled               625             550             88.0
created                  5               5            100.0
delivered            96478               2              0.0
invoiced               314             314            100.0
processing             301             301            100.0
shipped               1107               0              0.0
unavailable            609             609            100.0

--- order_delivered_customer_date ---
              total_orders  missing_values  missing_percent
order_status
approved                 2               2           100.00
canceled               625             619            99.04
created                  5               5           100.00
delivered            96478               8             0.01
invoiced               314             314           100.00
processing             301             301           100.00
shipped               1107            1107           100.00
unavailable            609             609           100.00

### Data Quality Check: Missing Values in Order Timestamps

**Dataset:** Olist Orders

**Columns investigated:**
- `order_approved_at`
- `order_delivered_carrier_date`
- `order_delivered_customer_date`

**Findings:**
- `order_approved_at`: 160 missing values (0.16%).
- `order_delivered_carrier_date`: 1,783 missing values (1.79%).
- `order_delivered_customer_date`: 2,965 missing values (2.98%).

The missing values were compared with `order_status`. Many appear consistent with orders that did not reach the corresponding stage of the purchasing or delivery process. However, some records marked as delivered are missing delivery timestamps and require further investigation.

**Cleaning decision:** Retain the missing values at this stage. Do not replace missing timestamps with estimated or average dates. Investigate delivered orders with incomplete timestamps and consider the availability of relevant dates when calculating delivery KPIs.

**Status:** Initial investigation completed; anomalous records under review.

-----------------------------------------------------------------------------------------------------------------------------------------

# olist customers dataset

In [9]:
customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")