In [1]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

In [3]:
# First rows
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [4]:
# Number of rows and columns
print("Shape:", sellers.shape)

# Column names
print("Columns:", sellers.columns.tolist())

# Data types and non-null counts
sellers.info()

# Statistical summary
sellers.describe()

Shape: (3095, 4)
Columns: ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']
<class 'pandas.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   str
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   str
 3   seller_state            3095 non-null   str
dtypes: int64(1), str(3)
memory usage: 96.8 KB

       seller_zip_code_prefix
count             3095.000000
mean             32291.059451
std              32713.453830
min               1001.000000
25%               7093.500000
50%              14940.000000
75%              64552.500000
max              99730.000000

In [5]:

# 1. Check missing values
print("Missing values:")
print(sellers.isnull().sum())

# 2. Check duplicate rows
print("\nFully duplicated rows:", sellers.duplicated().sum())

# 3. Check duplicate seller IDs
print("Duplicate seller IDs:", sellers["seller_id"].duplicated().sum())

# 4. Check ZIP code prefix formatting and range
print("\nZIP code prefix summary:")
print(sellers["seller_zip_code_prefix"].describe())

print("\nZIP prefixes with fewer than 5 digits:")
print(
    sellers[
        sellers["seller_zip_code_prefix"].astype(str).str.len() < 5
    ]["seller_zip_code_prefix"].head(10)
)

# 5. Check unique cities and states
print("\nUnique cities:", sellers["seller_city"].nunique())
print("Unique states:", sellers["seller_state"].nunique())

print("\nSeller state counts:")
print(sellers["seller_state"].value_counts())

# 6. Check text formatting
print("\nBlank seller cities:",
      sellers["seller_city"].str.strip().eq("").sum())

print("Blank seller states:",
      sellers["seller_state"].str.strip().eq("").sum())

Missing values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Fully duplicated rows: 0
Duplicate seller IDs: 0

ZIP code prefix summary:
count     3095.000000
mean     32291.059451
std      32713.453830
min       1001.000000
25%       7093.500000
50%      14940.000000
75%      64552.500000
max      99730.000000
Name: seller_zip_code_prefix, dtype: float64

ZIP prefixes with fewer than 5 digits:
3     4195
8     1529
12    1222
13    5372
19    5138
22    4156
27    9850
28    4857
31    2261
33    3562
Name: seller_zip_code_prefix, dtype: int64

Unique cities: 611
Unique states: 23

Seller state counts:
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
MA       1
AM       1
PA       1
Name: count, dtype: int64

Blank seller cities: 0
Blank seller states: 0

In [6]:

# Create a copy for cleaning
sellers_cleaned = sellers.copy()

# 1. Convert ZIP code prefixes to strings
# and ensure they have five digits
sellers_cleaned["seller_zip_code_prefix"] = (
    sellers_cleaned["seller_zip_code_prefix"]
    .astype(str)
    .str.zfill(5)
)

# 2. Standardize city names
sellers_cleaned["seller_city"] = (
    sellers_cleaned["seller_city"].str.strip()
)

# 3. Standardize state abbreviations
sellers_cleaned["seller_state"] = (
    sellers_cleaned["seller_state"].str.strip().str.upper()
)

# 4. Check the results
print("Original shape:", sellers.shape)
print("Cleaned shape:", sellers_cleaned.shape)

print("\nUpdated data types:")
print(sellers_cleaned.dtypes)

print("\nMissing values:")
print(sellers_cleaned.isnull().sum())

print("\nDuplicate seller IDs:",
      sellers_cleaned["seller_id"].duplicated().sum())

print("\nZIP code prefix examples:")
print(sellers_cleaned["seller_zip_code_prefix"].head(10))

print("\nPreview:")
print(sellers_cleaned.head())

Original shape: (3095, 4)
Cleaned shape: (3095, 4)

Updated data types:
seller_id                 str
seller_zip_code_prefix    str
seller_city               str
seller_state              str
dtype: object

Missing values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Duplicate seller IDs: 0

ZIP code prefix examples:
0    13023
1    13844
2    20031
3    04195
4    12914
5    20920
6    55325
7    16304
8    01529
9    80310
Name: seller_zip_code_prefix, dtype: str

Preview:
                          seller_id seller_zip_code_prefix        seller_city  \
0  3442f8959a84dea7ee197c632cb2df15                  13023           campinas
1  d1b65fc7debc3361ea86b5f14c68d2e2                  13844         mogi guacu
2  ce3ad9de960102d0677a81f5d0bb7b2d                  20031     rio de janeiro
3  c0f3eea2e14555b6faeea3dd58c1b1c3                  04195          sao paulo
4  51a04a8a6bdcb23deccc82b0b80742cf                  12914  braganca paulista

  seller_state
0           SP
1           SP
2           RJ
3           SP
4           SP

In [8]:
sellers_cleaned.to_csv("sellers_cleaned.csv", index=False)

print("Sellers dataset saved successfully!")

Sellers dataset saved successfully!

Sellers Dataset – Data Cleaning Summary

The Olist sellers dataset originally contained 3,095 rows and 4 columns.

Cleaning Steps

Checked for missing values; none were found.
Checked for duplicate rows and duplicate seller IDs; none were found.
Checked city and state columns for blank values; none were found.
Converted seller_zip_code_prefix from integer to string to preserve its identifier format.
Used .str.zfill(5) to ensure all ZIP code prefixes contain five digits.
Used .str.strip() to remove unnecessary leading and trailing spaces from city and state names.
Standardized state abbreviations to uppercase.
Final Result

The cleaned dataset retains all 3,095 rows and 4 columns. No seller records were deleted. The cleaned version is saved as sellers_cleaned.csv, while the original dataset remains unchanged.

Relevance to Research

This dataset will help connect sellers to marketplace transactions through seller_id and support Research Question 6, which explores whether seller acquisition information can be connected to marketplace performance.